// ESS ERIC / Sikt documentation excerpts: CC BY-SA 4.0.
// Generated from data/politikprofil-v2.2.ergaenzung.json by generate-public-catalogue-v22.mjs. Do not edit by hand.
import type { PublicItem } from './catalogue-types';
import { freezePublicMetadata } from './catalogue-types';

export const PUBLIC_CATALOGUE_V22: {
  readonly sourceSha256: string;
  readonly items: readonly PublicItem[];
} = freezePublicMetadata({
  sourceSha256: 'c4b0d97aeaf10868001199cb3f7f135a6fb8ec28d63b58f7f222ff7e0acd71ac',
  items: [
    {
      id: 'ESS8e02_3:elgcoal',
      studyId: 'ESS8e02_3',
      variable: 'elgcoal',
      primaryTheme: 'climate_energy',
      originalQuestionId: 'D4',
      wordingDe:
        'Wie viel des Stroms, der in Deutschland verbraucht wird, sollte aus Kohle erzeugt werden?',
      introductionsDe: [
        'Im grauen Kasten oben auf dieser Liste sehen Sie verschiedene Energiequellen, aus denen Strom erzeugt werden kann. Bitte lesen Sie diese kurz durch.',
      ],
      definitionDe: [],
      contextNotes: [
        'Code 55 wurde im Interview nicht vorgelesen (Kategorie in Klammern). Die Website bietet ihn nicht als Antwort an; in historischen Referenzen bleibt er eine eigene gültige Kategorie.',
        'Interviewerhinweis nur auf Nachfrage: Kohle umfasst Steinkohle und Braunkohle.',
      ],
      responseStemDe:
        'Wie viel des Stroms, der in Deutschland verbraucht wird, sollte aus jeder dieser Energiequellen erzeugt werden?',
      situationDe: null,
      instructionDe: null,
      groupId: 'electricity_sources',
      originalOrderInGroup: 1,
      responseType: 'ordered_amount',
      sourceRefs: [
        {
          sourceId: 'ess8-de-questionnaire',
          pdfPages: [27, 28],
          originalForm: null,
          listLabelDe: null,
        },
        {
          sourceId: 'ess8-de-showcards',
          pdfPages: [36],
          originalForm: null,
          listLabelDe: 'Liste 35',
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'Eine sehr große Menge',
          labelEn: 'A very large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'Eine große Menge',
          labelEn: 'A large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'Eine mittelgroße Menge',
          labelEn: 'A medium amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'Eine kleine Menge',
          labelEn: 'A small amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: 'Überhaupt nichts',
          labelEn: 'None at all',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '55',
          printedCodeDe: '55',
          labelDe: 'Ich habe noch nie etwas von dieser Energiequelle gehört',
          labelEn: 'I have not heard of this energy source before',
          isMissingApi: false,
          semanticRole: 'unprompted_nonposition',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: false,
        },
      ],
      boundOriginalForm: 'Nationales Interviewskript (CAPI)',
      codeBinding: {
        sourceId: 'ess8-original-codelists-direct',
        sourceFieldId: '122b2d2a-d875-4da2-bddb-0d6ecb9d9e2a',
        sourceFieldMetadataVersion: 4,
        dataFileMetadataId: 'ffc43f48-e15a-4a1c-8813-47eda377c355',
        dataFileMetadataVersion: 98,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5', '55'],
      missingCodes: [
        {
          code: '77',
          reasonApi: 'Refusal',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '88',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '99',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS8e02_3:elgngas',
      studyId: 'ESS8e02_3',
      variable: 'elgngas',
      primaryTheme: 'climate_energy',
      originalQuestionId: 'D5',
      wordingDe: 'Und wie viel aus Erdgas?',
      introductionsDe: [
        'Im grauen Kasten oben auf dieser Liste sehen Sie verschiedene Energiequellen, aus denen Strom erzeugt werden kann. Bitte lesen Sie diese kurz durch.',
      ],
      definitionDe: [],
      contextNotes: [
        'Code 55 wurde im Interview nicht vorgelesen (Kategorie in Klammern). Die Website bietet ihn nicht als Antwort an; in historischen Referenzen bleibt er eine eigene gültige Kategorie.',
        'Interviewerhinweis nur auf Nachfrage: Kohle umfasst Steinkohle und Braunkohle.',
      ],
      responseStemDe:
        'Wie viel des Stroms, der in Deutschland verbraucht wird, sollte aus jeder dieser Energiequellen erzeugt werden?',
      situationDe: null,
      instructionDe: null,
      groupId: 'electricity_sources',
      originalOrderInGroup: 2,
      responseType: 'ordered_amount',
      sourceRefs: [
        {
          sourceId: 'ess8-de-questionnaire',
          pdfPages: [27, 28],
          originalForm: null,
          listLabelDe: null,
        },
        {
          sourceId: 'ess8-de-showcards',
          pdfPages: [36],
          originalForm: null,
          listLabelDe: 'Liste 35',
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'Eine sehr große Menge',
          labelEn: 'A very large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'Eine große Menge',
          labelEn: 'A large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'Eine mittelgroße Menge',
          labelEn: 'A medium amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'Eine kleine Menge',
          labelEn: 'A small amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: 'Überhaupt nichts',
          labelEn: 'None at all',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '55',
          printedCodeDe: '55',
          labelDe: 'Ich habe noch nie etwas von dieser Energiequelle gehört',
          labelEn: 'I have not heard of this energy source before',
          isMissingApi: false,
          semanticRole: 'unprompted_nonposition',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: false,
        },
      ],
      boundOriginalForm: 'Nationales Interviewskript (CAPI)',
      codeBinding: {
        sourceId: 'ess8-original-codelists-direct',
        sourceFieldId: '185da5fe-2251-46e6-ad02-977bdd9695c4',
        sourceFieldMetadataVersion: 4,
        dataFileMetadataId: 'ffc43f48-e15a-4a1c-8813-47eda377c355',
        dataFileMetadataVersion: 98,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5', '55'],
      missingCodes: [
        {
          code: '77',
          reasonApi: 'Refusal',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '88',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '99',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS8e02_3:elghydr',
      studyId: 'ESS8e02_3',
      variable: 'elghydr',
      primaryTheme: 'climate_energy',
      originalQuestionId: 'D6',
      wordingDe: 'Und wie viel aus Wasserkraft, also aus Flüssen, Stauseen oder dem Meer?',
      introductionsDe: [
        'Im grauen Kasten oben auf dieser Liste sehen Sie verschiedene Energiequellen, aus denen Strom erzeugt werden kann. Bitte lesen Sie diese kurz durch.',
      ],
      definitionDe: [],
      contextNotes: [
        'Code 55 wurde im Interview nicht vorgelesen (Kategorie in Klammern). Die Website bietet ihn nicht als Antwort an; in historischen Referenzen bleibt er eine eigene gültige Kategorie.',
        'Interviewerhinweis nur auf Nachfrage: Kohle umfasst Steinkohle und Braunkohle.',
      ],
      responseStemDe:
        'Wie viel des Stroms, der in Deutschland verbraucht wird, sollte aus jeder dieser Energiequellen erzeugt werden?',
      situationDe: null,
      instructionDe: null,
      groupId: 'electricity_sources',
      originalOrderInGroup: 3,
      responseType: 'ordered_amount',
      sourceRefs: [
        {
          sourceId: 'ess8-de-questionnaire',
          pdfPages: [27, 28],
          originalForm: null,
          listLabelDe: null,
        },
        {
          sourceId: 'ess8-de-showcards',
          pdfPages: [36],
          originalForm: null,
          listLabelDe: 'Liste 35',
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'Eine sehr große Menge',
          labelEn: 'A very large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'Eine große Menge',
          labelEn: 'A large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'Eine mittelgroße Menge',
          labelEn: 'A medium amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'Eine kleine Menge',
          labelEn: 'A small amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: 'Überhaupt nichts',
          labelEn: 'None at all',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '55',
          printedCodeDe: '55',
          labelDe: 'Ich habe noch nie etwas von dieser Energiequelle gehört',
          labelEn: 'I have not heard of this energy source before',
          isMissingApi: false,
          semanticRole: 'unprompted_nonposition',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: false,
        },
      ],
      boundOriginalForm: 'Nationales Interviewskript (CAPI)',
      codeBinding: {
        sourceId: 'ess8-original-codelists-direct',
        sourceFieldId: 'f3e020e2-f635-4946-9a7d-90a424448714',
        sourceFieldMetadataVersion: 4,
        dataFileMetadataId: 'ffc43f48-e15a-4a1c-8813-47eda377c355',
        dataFileMetadataVersion: 98,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5', '55'],
      missingCodes: [
        {
          code: '77',
          reasonApi: 'Refusal',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '88',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '99',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS8e02_3:elgnuc',
      studyId: 'ESS8e02_3',
      variable: 'elgnuc',
      primaryTheme: 'climate_energy',
      originalQuestionId: 'D7',
      wordingDe:
        'Wie viel des Stroms, der in Deutschland verbraucht wird, sollte aus Atomkraft bzw. Kernkraft erzeugt werden?',
      introductionsDe: [
        'Im grauen Kasten oben auf dieser Liste sehen Sie verschiedene Energiequellen, aus denen Strom erzeugt werden kann. Bitte lesen Sie diese kurz durch.',
      ],
      definitionDe: [],
      contextNotes: [
        'Code 55 wurde im Interview nicht vorgelesen (Kategorie in Klammern). Die Website bietet ihn nicht als Antwort an; in historischen Referenzen bleibt er eine eigene gültige Kategorie.',
        'Interviewerhinweis nur auf Nachfrage: Kohle umfasst Steinkohle und Braunkohle.',
      ],
      responseStemDe:
        'Wie viel des Stroms, der in Deutschland verbraucht wird, sollte aus jeder dieser Energiequellen erzeugt werden?',
      situationDe: null,
      instructionDe: null,
      groupId: 'electricity_sources',
      originalOrderInGroup: 4,
      responseType: 'ordered_amount',
      sourceRefs: [
        {
          sourceId: 'ess8-de-questionnaire',
          pdfPages: [27, 28],
          originalForm: null,
          listLabelDe: null,
        },
        {
          sourceId: 'ess8-de-showcards',
          pdfPages: [36],
          originalForm: null,
          listLabelDe: 'Liste 35',
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'Eine sehr große Menge',
          labelEn: 'A very large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'Eine große Menge',
          labelEn: 'A large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'Eine mittelgroße Menge',
          labelEn: 'A medium amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'Eine kleine Menge',
          labelEn: 'A small amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: 'Überhaupt nichts',
          labelEn: 'None at all',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '55',
          printedCodeDe: '55',
          labelDe: 'Ich habe noch nie etwas von dieser Energiequelle gehört',
          labelEn: 'I have not heard of this energy source before',
          isMissingApi: false,
          semanticRole: 'unprompted_nonposition',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: false,
        },
      ],
      boundOriginalForm: 'Nationales Interviewskript (CAPI)',
      codeBinding: {
        sourceId: 'ess8-original-codelists-direct',
        sourceFieldId: '477eede3-1055-41c1-a842-fe0a716c13ae',
        sourceFieldMetadataVersion: 4,
        dataFileMetadataId: 'ffc43f48-e15a-4a1c-8813-47eda377c355',
        dataFileMetadataVersion: 98,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5', '55'],
      missingCodes: [
        {
          code: '77',
          reasonApi: 'Refusal',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '88',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '99',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS8e02_3:elgsun',
      studyId: 'ESS8e02_3',
      variable: 'elgsun',
      primaryTheme: 'climate_energy',
      originalQuestionId: 'D8',
      wordingDe: 'Und wie viel aus Sonnenenergie?',
      introductionsDe: [
        'Im grauen Kasten oben auf dieser Liste sehen Sie verschiedene Energiequellen, aus denen Strom erzeugt werden kann. Bitte lesen Sie diese kurz durch.',
      ],
      definitionDe: [],
      contextNotes: [
        'Code 55 wurde im Interview nicht vorgelesen (Kategorie in Klammern). Die Website bietet ihn nicht als Antwort an; in historischen Referenzen bleibt er eine eigene gültige Kategorie.',
        'Interviewerhinweis nur auf Nachfrage: Kohle umfasst Steinkohle und Braunkohle.',
      ],
      responseStemDe:
        'Wie viel des Stroms, der in Deutschland verbraucht wird, sollte aus jeder dieser Energiequellen erzeugt werden?',
      situationDe: null,
      instructionDe: null,
      groupId: 'electricity_sources',
      originalOrderInGroup: 5,
      responseType: 'ordered_amount',
      sourceRefs: [
        {
          sourceId: 'ess8-de-questionnaire',
          pdfPages: [27, 28],
          originalForm: null,
          listLabelDe: null,
        },
        {
          sourceId: 'ess8-de-showcards',
          pdfPages: [36],
          originalForm: null,
          listLabelDe: 'Liste 35',
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'Eine sehr große Menge',
          labelEn: 'A very large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'Eine große Menge',
          labelEn: 'A large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'Eine mittelgroße Menge',
          labelEn: 'A medium amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'Eine kleine Menge',
          labelEn: 'A small amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: 'Überhaupt nichts',
          labelEn: 'None at all',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '55',
          printedCodeDe: '55',
          labelDe: 'Ich habe noch nie etwas von dieser Energiequelle gehört',
          labelEn: 'I have not heard of this energy source before',
          isMissingApi: false,
          semanticRole: 'unprompted_nonposition',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: false,
        },
      ],
      boundOriginalForm: 'Nationales Interviewskript (CAPI)',
      codeBinding: {
        sourceId: 'ess8-original-codelists-direct',
        sourceFieldId: '2eeaeacc-0acd-4bc9-b429-b4a3c9008ef2',
        sourceFieldMetadataVersion: 4,
        dataFileMetadataId: 'ffc43f48-e15a-4a1c-8813-47eda377c355',
        dataFileMetadataVersion: 98,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5', '55'],
      missingCodes: [
        {
          code: '77',
          reasonApi: 'Refusal',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '88',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '99',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS8e02_3:elgwind',
      studyId: 'ESS8e02_3',
      variable: 'elgwind',
      primaryTheme: 'climate_energy',
      originalQuestionId: 'D9',
      wordingDe: 'Und wie viel aus Windkraft?',
      introductionsDe: [
        'Im grauen Kasten oben auf dieser Liste sehen Sie verschiedene Energiequellen, aus denen Strom erzeugt werden kann. Bitte lesen Sie diese kurz durch.',
      ],
      definitionDe: [],
      contextNotes: [
        'Code 55 wurde im Interview nicht vorgelesen (Kategorie in Klammern). Die Website bietet ihn nicht als Antwort an; in historischen Referenzen bleibt er eine eigene gültige Kategorie.',
        'Interviewerhinweis nur auf Nachfrage: Kohle umfasst Steinkohle und Braunkohle.',
      ],
      responseStemDe:
        'Wie viel des Stroms, der in Deutschland verbraucht wird, sollte aus jeder dieser Energiequellen erzeugt werden?',
      situationDe: null,
      instructionDe: null,
      groupId: 'electricity_sources',
      originalOrderInGroup: 6,
      responseType: 'ordered_amount',
      sourceRefs: [
        {
          sourceId: 'ess8-de-questionnaire',
          pdfPages: [27, 28],
          originalForm: null,
          listLabelDe: null,
        },
        {
          sourceId: 'ess8-de-showcards',
          pdfPages: [36],
          originalForm: null,
          listLabelDe: 'Liste 35',
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'Eine sehr große Menge',
          labelEn: 'A very large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'Eine große Menge',
          labelEn: 'A large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'Eine mittelgroße Menge',
          labelEn: 'A medium amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'Eine kleine Menge',
          labelEn: 'A small amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: 'Überhaupt nichts',
          labelEn: 'None at all',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '55',
          printedCodeDe: '55',
          labelDe: 'Ich habe noch nie etwas von dieser Energiequelle gehört',
          labelEn: 'I have not heard of this energy source before',
          isMissingApi: false,
          semanticRole: 'unprompted_nonposition',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: false,
        },
      ],
      boundOriginalForm: 'Nationales Interviewskript (CAPI)',
      codeBinding: {
        sourceId: 'ess8-original-codelists-direct',
        sourceFieldId: '0998be50-cb4f-40d1-88f7-02c8bab35626',
        sourceFieldMetadataVersion: 4,
        dataFileMetadataId: 'ffc43f48-e15a-4a1c-8813-47eda377c355',
        dataFileMetadataVersion: 98,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5', '55'],
      missingCodes: [
        {
          code: '77',
          reasonApi: 'Refusal',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '88',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '99',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS8e02_3:elgbio',
      studyId: 'ESS8e02_3',
      variable: 'elgbio',
      primaryTheme: 'climate_energy',
      originalQuestionId: 'D10',
      wordingDe:
        'Und wie viel Strom sollte aus Biomasse wie Holz, Pflanzen oder Tiermist gewonnen werden?',
      introductionsDe: [
        'Im grauen Kasten oben auf dieser Liste sehen Sie verschiedene Energiequellen, aus denen Strom erzeugt werden kann. Bitte lesen Sie diese kurz durch.',
      ],
      definitionDe: [],
      contextNotes: [
        'Code 55 wurde im Interview nicht vorgelesen (Kategorie in Klammern). Die Website bietet ihn nicht als Antwort an; in historischen Referenzen bleibt er eine eigene gültige Kategorie.',
        'Interviewerhinweis nur auf Nachfrage: Kohle umfasst Steinkohle und Braunkohle.',
      ],
      responseStemDe:
        'Wie viel des Stroms, der in Deutschland verbraucht wird, sollte aus jeder dieser Energiequellen erzeugt werden?',
      situationDe: null,
      instructionDe: null,
      groupId: 'electricity_sources',
      originalOrderInGroup: 7,
      responseType: 'ordered_amount',
      sourceRefs: [
        {
          sourceId: 'ess8-de-questionnaire',
          pdfPages: [27, 28],
          originalForm: null,
          listLabelDe: null,
        },
        {
          sourceId: 'ess8-de-showcards',
          pdfPages: [36],
          originalForm: null,
          listLabelDe: 'Liste 35',
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'Eine sehr große Menge',
          labelEn: 'A very large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'Eine große Menge',
          labelEn: 'A large amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'Eine mittelgroße Menge',
          labelEn: 'A medium amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'Eine kleine Menge',
          labelEn: 'A small amount',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: 'Überhaupt nichts',
          labelEn: 'None at all',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '55',
          printedCodeDe: '55',
          labelDe: 'Ich habe noch nie etwas von dieser Energiequelle gehört',
          labelEn: 'I have not heard of this energy source before',
          isMissingApi: false,
          semanticRole: 'unprompted_nonposition',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: false,
        },
      ],
      boundOriginalForm: 'Nationales Interviewskript (CAPI)',
      codeBinding: {
        sourceId: 'ess8-original-codelists-direct',
        sourceFieldId: '1c795821-5b61-4382-8a6b-9f31cb2fbba5',
        sourceFieldMetadataVersion: 4,
        dataFileMetadataId: 'ffc43f48-e15a-4a1c-8813-47eda377c355',
        dataFileMetadataVersion: 98,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5', '55'],
      missingCodes: [
        {
          code: '77',
          reasonApi: 'Refusal',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '88',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '99',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS8e02_3:gvrfgap',
      studyId: 'ESS8e02_3',
      variable: 'gvrfgap',
      primaryTheme: 'migration',
      originalQuestionId: 'C42',
      wordingDe: 'Bei der Prüfung von Asylanträgen sollte der Staat großzügig sein.',
      introductionsDe: [
        'Es gibt Menschen, die nach Deutschland kommen und Asyl beantragen, weil sie in ihrem eigenen Land Angst vor Verfolgung haben.',
        'Bitte sagen Sie mir anhand von Liste 31, wie sehr Sie jeder der folgenden Aussagen zustimmen oder wie sehr Sie diese ablehnen.',
      ],
      definitionDe: [],
      contextNotes: [
        'Der Fragebogen druckt die Codes 0–5; Liste 31 hat fünf beschriftete Stufen. Gebunden sind die Beschriftungen der Liste 31 und die API-Codes 1–5.',
      ],
      responseStemDe: null,
      situationDe: null,
      instructionDe: null,
      groupId: 'asylum',
      originalOrderInGroup: 1,
      responseType: 'ordered_agreement',
      sourceRefs: [
        {
          sourceId: 'ess8-de-questionnaire',
          pdfPages: [25],
          originalForm: null,
          listLabelDe: null,
        },
        {
          sourceId: 'ess8-de-showcards',
          pdfPages: [32],
          originalForm: null,
          listLabelDe: 'Liste 31',
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: null,
          labelDe: 'Stimme stark zu',
          labelEn: 'Agree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: null,
          labelDe: 'Stimme zu',
          labelEn: 'Agree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: null,
          labelDe: 'Weder noch',
          labelEn: 'Neither agree nor disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: null,
          labelDe: 'Lehne ab',
          labelEn: 'Disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: null,
          labelDe: 'Lehne stark ab',
          labelEn: 'Disagree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
      ],
      boundOriginalForm: 'Nationales Interviewskript (CAPI)',
      codeBinding: {
        sourceId: 'ess8-original-codelists-direct',
        sourceFieldId: '6fbced30-27a9-4e84-b24c-6562df4859e3',
        sourceFieldMetadataVersion: 1,
        dataFileMetadataId: 'ffc43f48-e15a-4a1c-8813-47eda377c355',
        dataFileMetadataVersion: 98,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5'],
      missingCodes: [
        { code: '7', reasonApi: 'Refusal', isMissingApi: true, printedCodeDe: null, labelDe: null },
        {
          code: '8',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '9',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS8e02_3:rfgbfml',
      studyId: 'ESS8e02_3',
      variable: 'rfgbfml',
      primaryTheme: 'migration',
      originalQuestionId: 'C44',
      wordingDe:
        'Asylbewerber, deren Anträge bewilligt wurden, sollten das Recht haben, ihre engen Familienangehörigen nach Deutschland zu holen.',
      introductionsDe: [
        'Es gibt Menschen, die nach Deutschland kommen und Asyl beantragen, weil sie in ihrem eigenen Land Angst vor Verfolgung haben.',
        'Bitte sagen Sie mir anhand von Liste 31, wie sehr Sie jeder der folgenden Aussagen zustimmen oder wie sehr Sie diese ablehnen.',
      ],
      definitionDe: [],
      contextNotes: [
        'Der Fragebogen druckt die Codes 0–5; Liste 31 hat fünf beschriftete Stufen. Gebunden sind die Beschriftungen der Liste 31 und die API-Codes 1–5.',
        'C43 (Wahrnehmung der Verfolgungsangst) liegt zwischen C42 und C44 und ist nicht ausgewählt.',
      ],
      responseStemDe: null,
      situationDe: null,
      instructionDe: null,
      groupId: 'asylum',
      originalOrderInGroup: 2,
      responseType: 'ordered_agreement',
      sourceRefs: [
        {
          sourceId: 'ess8-de-questionnaire',
          pdfPages: [25],
          originalForm: null,
          listLabelDe: null,
        },
        {
          sourceId: 'ess8-de-showcards',
          pdfPages: [32],
          originalForm: null,
          listLabelDe: 'Liste 31',
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: null,
          labelDe: 'Stimme stark zu',
          labelEn: 'Agree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: null,
          labelDe: 'Stimme zu',
          labelEn: 'Agree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: null,
          labelDe: 'Weder noch',
          labelEn: 'Neither agree nor disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: null,
          labelDe: 'Lehne ab',
          labelEn: 'Disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: null,
          labelDe: 'Lehne stark ab',
          labelEn: 'Disagree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
      ],
      boundOriginalForm: 'Nationales Interviewskript (CAPI)',
      codeBinding: {
        sourceId: 'ess8-original-codelists-direct',
        sourceFieldId: '77283f87-427a-4e4c-a0b8-1ccb7b55b976',
        sourceFieldMetadataVersion: 1,
        dataFileMetadataId: 'ffc43f48-e15a-4a1c-8813-47eda377c355',
        dataFileMetadataVersion: 98,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5'],
      missingCodes: [
        { code: '7', reasonApi: 'Refusal', isMissingApi: true, printedCodeDe: null, labelDe: null },
        {
          code: '8',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '9',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS8e02_3:basinc',
      studyId: 'ESS8e02_3',
      variable: 'basinc',
      primaryTheme: 'welfare',
      originalQuestionId: 'E36',
      wordingDe:
        'Alles in allem, wären Sie gegen oder für ein solches Grundeinkommen in Deutschland?',
      introductionsDe: [
        'In einigen Ländern wird momentan über die Einführung eines Grundeinkommens diskutiert. Ich werde Sie gleich fragen, ob Sie gegen oder für ein solches Grundeinkommen sind. Zuerst aber ein paar Einzelheiten dazu.',
        'Im grauen Kasten oben auf Liste 54 sehen Sie die wichtigsten Eigenschaften. Ein solches Grundeinkommen umfasst alle folgenden Punkte:',
      ],
      definitionDe: [
        'Der Staat zahlt jedem ein monatliches Einkommen, das alle grundlegenden Lebenshaltungskosten deckt.',
        'Dadurch werden viele bestehende Sozialleistungen ersetzt.',
        'Das Ziel ist es, jedem einen minimalen Lebensstandard zu garantieren.',
        'Alle erhalten den gleichen Betrag, egal ob man arbeitet oder nicht.',
        'Man kann zudem das Einkommen aus Erwerbstätigkeit oder anderen Quellen behalten.',
        'Das Grundeinkommen wird über Steuern finanziert.',
      ],
      contextNotes: ['Die Einleitung nennt eine Diskussion „momentan“, also zur Feldzeit 2016/17.'],
      responseStemDe: null,
      situationDe: null,
      instructionDe: null,
      groupId: 'basic_income',
      originalOrderInGroup: 1,
      responseType: 'ordered_support',
      sourceRefs: [
        {
          sourceId: 'ess8-de-questionnaire',
          pdfPages: [43],
          originalForm: null,
          listLabelDe: null,
        },
        {
          sourceId: 'ess8-de-showcards',
          pdfPages: [55],
          originalForm: null,
          listLabelDe: 'Liste 54',
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'Sehr dagegen',
          labelEn: 'Strongly against',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'Dagegen',
          labelEn: 'Against',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'Dafür',
          labelEn: 'In favour',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'Sehr dafür',
          labelEn: 'Strongly in favour',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
      ],
      boundOriginalForm: 'Nationales Interviewskript (CAPI)',
      codeBinding: {
        sourceId: 'ess8-original-codelists-direct',
        sourceFieldId: '53924781-bca7-49b6-8245-1a2112576526',
        sourceFieldMetadataVersion: 2,
        dataFileMetadataId: 'ffc43f48-e15a-4a1c-8813-47eda377c355',
        dataFileMetadataVersion: 98,
      },
      apiValidCodeOrder: ['1', '2', '3', '4'],
      missingCodes: [
        { code: '7', reasonApi: 'Refusal', isMissingApi: true, printedCodeDe: null, labelDe: null },
        {
          code: '8',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '9',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS8e02_3:eusclbf',
      studyId: 'ESS8e02_3',
      variable: 'eusclbf',
      primaryTheme: 'europe',
      originalQuestionId: 'E37',
      wordingDe:
        'Alles in allem, wären Sie gegen oder für ein solches EU-weites Sozialleistungsprogramm?',
      introductionsDe: [
        'Es gibt den Vorschlag in der gesamten Europäischen Union ein Programm mit Sozialleistungen für alle armen Menschen einzuführen. Ich werde Sie gleich fragen, ob Sie gegen oder für ein solches Programm sind.',
        'Im grauen Kasten oben auf Liste 55 sehen Sie die wichtigsten Eigenschaften.',
        'Ein solches EU-weites Sozialleistungsprogramm umfasst alle der folgenden Punkte:',
      ],
      definitionDe: [
        'Das Ziel ist es, einen minimalen Lebensstandard für alle armen Menschen in der EU zu garantieren.',
        'Die Höhe der Sozialleistungen wird an die Lebenshaltungskosten im jeweiligen Land angepasst.',
        'Das Programm erfordert, dass reichere EU-Länder mehr zur Finanzierung der Sozialleistungen beitragen als ärmere EU-Länder.',
      ],
      contextNotes: [],
      responseStemDe: null,
      situationDe: null,
      instructionDe: null,
      groupId: 'eu_social_benefit',
      originalOrderInGroup: 1,
      responseType: 'ordered_support',
      sourceRefs: [
        {
          sourceId: 'ess8-de-questionnaire',
          pdfPages: [44],
          originalForm: null,
          listLabelDe: null,
        },
        {
          sourceId: 'ess8-de-showcards',
          pdfPages: [56],
          originalForm: null,
          listLabelDe: 'Liste 55',
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'Sehr dagegen',
          labelEn: 'Strongly against',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'Dagegen',
          labelEn: 'Against',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'Dafür',
          labelEn: 'In favour',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'Sehr dafür',
          labelEn: 'Strongly in favour',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
      ],
      boundOriginalForm: 'Nationales Interviewskript (CAPI)',
      codeBinding: {
        sourceId: 'ess8-original-codelists-direct',
        sourceFieldId: 'c26d4daf-81ab-4621-8625-8613b57abfc7',
        sourceFieldMetadataVersion: 2,
        dataFileMetadataId: 'ffc43f48-e15a-4a1c-8813-47eda377c355',
        dataFileMetadataVersion: 98,
      },
      apiValidCodeOrder: ['1', '2', '3', '4'],
      missingCodes: [
        { code: '7', reasonApi: 'Refusal', isMissingApi: true, printedCodeDe: null, labelDe: null },
        {
          code: '8',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '9',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS10SCe03_2:panpriph',
      studyId: 'ESS10SCe03_2',
      variable: 'panpriph',
      primaryTheme: 'rights_security',
      originalQuestionId: 'A1',
      wordingDe:
        'Ist es bei der Bekämpfung einer Pandemie wichtiger, die Gesundheit der Bevölkerung oder die Wirtschaft vorrangig zu berücksichtigen?',
      introductionsDe: [
        'In diesem ersten Teil werden wir Ihnen Fragen zu einer Auswahl verschiedener Themen stellen, zunächst zu Pandemien.',
      ],
      definitionDe: [],
      contextNotes: [
        'Bitte beantworten Sie alle Fragen nach dem heutigen Stand der Dinge, auch wenn dieser durch die Pandemie anders ist als sonst.',
        'Erhoben 2021/22 während der Coronavirus-Pandemie.',
      ],
      responseStemDe: null,
      situationDe: null,
      instructionDe:
        'Bitte markieren Sie einen Kreis von 0 bis 10. 0 bedeutet, dass es viel wichtiger ist, die Gesundheit der Bevölkerung vorrangig zu berücksichtigen, und 10 bedeutet, dass es viel wichtiger ist, die Wirtschaft vorrangig zu berücksichtigen.',
      groupId: 'pandemic_tradeoffs',
      originalOrderInGroup: 1,
      responseType: 'ordered_tradeoff',
      sourceRefs: [
        {
          sourceId: 'ess10-de-questionnaire',
          pdfPages: [2],
          originalForm: null,
          listLabelDe: null,
        },
      ],
      categories: [
        {
          code: '0',
          printedCodeDe: '0',
          labelDe: 'Viel wichtiger, die Gesundheit der Bevölkerung vorrangig zu berücksichtigen',
          labelEn: 'Much more important to prioritise public health',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: '1',
          labelEn: '1',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: '2',
          labelEn: '2',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: '3',
          labelEn: '3',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: '4',
          labelEn: '4',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: '5',
          labelEn: '5',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '6',
          printedCodeDe: '6',
          labelDe: '6',
          labelEn: '6',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '7',
          printedCodeDe: '7',
          labelDe: '7',
          labelEn: '7',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '8',
          printedCodeDe: '8',
          labelDe: '8',
          labelEn: '8',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '9',
          printedCodeDe: '9',
          labelDe: '9',
          labelEn: '9',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '10',
          printedCodeDe: '10',
          labelDe: 'Viel wichtiger, die Wirtschaft vorrangig zu berücksichtigen',
          labelEn: 'Much more important to prioritise economic activity',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
      ],
      boundOriginalForm: 'Gedruckter Papierfragebogen (Selbstausfüllung)',
      codeBinding: {
        sourceId: 'ess10sc-original-codelists-direct',
        sourceFieldId: '89e5ccb1-5c96-42ad-97a0-85e40a8df2c9',
        sourceFieldMetadataVersion: 3,
        dataFileMetadataId: '178d1c16-db15-466e-b1a5-cea36109e089',
        dataFileMetadataVersion: 147,
      },
      apiValidCodeOrder: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      missingCodes: [
        {
          code: '77',
          reasonApi: 'Refusal',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '88',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '99',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: ['66'],
    },
    {
      id: 'ESS10SCe03_2:panmonpb',
      studyId: 'ESS10SCe03_2',
      variable: 'panmonpb',
      primaryTheme: 'rights_security',
      originalQuestionId: 'A2',
      wordingDe:
        'Ist es bei der Bekämpfung einer Pandemie wichtiger, dass Regierungen die Bevölkerung überwachen und nachverfolgen oder die Privatsphäre des Einzelnen bewahren?',
      introductionsDe: [
        'In diesem ersten Teil werden wir Ihnen Fragen zu einer Auswahl verschiedener Themen stellen, zunächst zu Pandemien.',
      ],
      definitionDe: [],
      contextNotes: [
        'Bitte beantworten Sie alle Fragen nach dem heutigen Stand der Dinge, auch wenn dieser durch die Pandemie anders ist als sonst.',
        'Erhoben 2021/22 während der Coronavirus-Pandemie. Die Frage betrifft die Pandemiebekämpfung und deckt Digitalpolitik nicht ab.',
      ],
      responseStemDe: null,
      situationDe: null,
      instructionDe: null,
      groupId: 'pandemic_tradeoffs',
      originalOrderInGroup: 2,
      responseType: 'ordered_tradeoff',
      sourceRefs: [
        {
          sourceId: 'ess10-de-questionnaire',
          pdfPages: [2],
          originalForm: null,
          listLabelDe: null,
        },
      ],
      categories: [
        {
          code: '0',
          printedCodeDe: '0',
          labelDe: 'Viel wichtiger, die Bevölkerung zu überwachen und nachzuverfolgen',
          labelEn: 'Much more important to monitor and track the public',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: '1',
          labelEn: '1',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: '2',
          labelEn: '2',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: '3',
          labelEn: '3',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: '4',
          labelEn: '4',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: '5',
          labelEn: '5',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '6',
          printedCodeDe: '6',
          labelDe: '6',
          labelEn: '6',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '7',
          printedCodeDe: '7',
          labelDe: '7',
          labelEn: '7',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '8',
          printedCodeDe: '8',
          labelDe: '8',
          labelEn: '8',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '9',
          printedCodeDe: '9',
          labelDe: '9',
          labelEn: '9',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '10',
          printedCodeDe: '10',
          labelDe: 'Viel wichtiger, die Privatsphäre des Einzelnen zu bewahren',
          labelEn: 'Much more important to maintain public privacy',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
      ],
      boundOriginalForm: 'Gedruckter Papierfragebogen (Selbstausfüllung)',
      codeBinding: {
        sourceId: 'ess10sc-original-codelists-direct',
        sourceFieldId: '687254d2-5b24-41ba-9d55-169f1b3b22f5',
        sourceFieldMetadataVersion: 3,
        dataFileMetadataId: '178d1c16-db15-466e-b1a5-cea36109e089',
        dataFileMetadataVersion: 147,
      },
      apiValidCodeOrder: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      missingCodes: [
        {
          code: '77',
          reasonApi: 'Refusal',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '88',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '99',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: ['66'],
    },
    {
      id: 'ESS8e02_3:mnrgtjb',
      studyId: 'ESS8e02_3',
      variable: 'mnrgtjb',
      primaryTheme: 'equality_family',
      originalQuestionId: 'B33A',
      wordingDe:
        'Wenn Arbeitsplätze knapp sind, sollten Männer eher einen Anspruch auf einen Arbeitsplatz haben als Frauen.',
      introductionsDe: [
        'Bitte schauen Sie jetzt auf Liste 13 und sagen Sie mir, wie sehr Sie jeder der folgenden Aussagen zustimmen oder wie sehr Sie diese ablehnen.',
      ],
      definitionDe: [],
      contextNotes: [
        'Im Originalblock stehen davor die Frage zu Einkommensunterschieden (B33) und danach die Fragen zu Schwulen und Lesben (B34–B36).',
      ],
      responseStemDe: null,
      situationDe: null,
      instructionDe: null,
      groupId: 'job_rights_gender',
      originalOrderInGroup: 1,
      responseType: 'ordered_agreement',
      sourceRefs: [
        {
          sourceId: 'ess8-de-questionnaire',
          pdfPages: [12],
          originalForm: null,
          listLabelDe: null,
        },
        {
          sourceId: 'ess8-de-showcards',
          pdfPages: [14],
          originalForm: null,
          listLabelDe: 'Liste 13',
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'Stimme stark zu',
          labelEn: 'Agree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'Stimme zu',
          labelEn: 'Agree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'Weder noch',
          labelEn: 'Neither agree nor disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'Lehne ab',
          labelEn: 'Disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: 'Lehne stark ab',
          labelEn: 'Disagree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess8-de-showcards',
          offeredOnWebsite: true,
        },
      ],
      boundOriginalForm: 'Nationales Interviewskript (CAPI)',
      codeBinding: {
        sourceId: 'ess8-original-codelists-direct',
        sourceFieldId: '418694c6-c656-4ca7-943d-ffbe82c8f8ed',
        sourceFieldMetadataVersion: 1,
        dataFileMetadataId: 'ffc43f48-e15a-4a1c-8813-47eda377c355',
        dataFileMetadataVersion: 98,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5'],
      missingCodes: [
        { code: '7', reasonApi: 'Refusal', isMissingApi: true, printedCodeDe: null, labelDe: null },
        {
          code: '8',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '9',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS10SCe03_2:freehms',
      studyId: 'ESS10SCe03_2',
      variable: 'freehms',
      primaryTheme: 'equality_family',
      originalQuestionId: 'A47',
      wordingDe: 'Schwule und Lesben sollten ihr Leben so führen dürfen, wie sie es wollen.',
      introductionsDe: [
        'Wie sehr stimmen Sie jeder der folgenden Aussagen zu oder wie sehr lehnen Sie diese ab?',
        'Markieren Sie für jede Aussage ein Kästchen.',
      ],
      definitionDe: [],
      contextNotes: [
        'Bitte beantworten Sie alle Fragen nach dem heutigen Stand der Dinge, auch wenn dieser durch die Pandemie anders ist als sonst.',
      ],
      responseStemDe: null,
      situationDe: null,
      instructionDe: null,
      groupId: 'same_sex_couples',
      originalOrderInGroup: 1,
      responseType: 'ordered_agreement',
      sourceRefs: [
        {
          sourceId: 'ess10-de-questionnaire',
          pdfPages: [6],
          originalForm: null,
          listLabelDe: null,
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'Stimme stark zu',
          labelEn: 'Agree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'Stimme zu',
          labelEn: 'Agree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'Weder noch',
          labelEn: 'Neither agree nor disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'Lehne ab',
          labelEn: 'Disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: 'Lehne stark ab',
          labelEn: 'Disagree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
      ],
      boundOriginalForm: 'Gedruckter Papierfragebogen (Selbstausfüllung)',
      codeBinding: {
        sourceId: 'ess10sc-original-codelists-direct',
        sourceFieldId: '82b770ad-95ee-4371-810d-fcb662d8d132',
        sourceFieldMetadataVersion: 5,
        dataFileMetadataId: '178d1c16-db15-466e-b1a5-cea36109e089',
        dataFileMetadataVersion: 147,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5'],
      missingCodes: [
        { code: '7', reasonApi: 'Refusal', isMissingApi: true, printedCodeDe: null, labelDe: null },
        {
          code: '8',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '9',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS10SCe03_2:hmsacld',
      studyId: 'ESS10SCe03_2',
      variable: 'hmsacld',
      primaryTheme: 'equality_family',
      originalQuestionId: 'A49',
      wordingDe:
        'Schwule und lesbische Paare sollten die gleichen Rechte haben, Kinder zu adoptieren, wie Paare, die aus Mann und Frau bestehen.',
      introductionsDe: [
        'Wie sehr stimmen Sie jeder der folgenden Aussagen zu oder wie sehr lehnen Sie diese ab?',
        'Markieren Sie für jede Aussage ein Kästchen.',
      ],
      definitionDe: [],
      contextNotes: [
        'Bitte beantworten Sie alle Fragen nach dem heutigen Stand der Dinge, auch wenn dieser durch die Pandemie anders ist als sonst.',
        'A48 (eigene Scham bei einem schwulen oder lesbischen Familienmitglied) liegt zwischen A47 und A49 und ist nicht ausgewählt.',
      ],
      responseStemDe: null,
      situationDe: null,
      instructionDe: null,
      groupId: 'same_sex_couples',
      originalOrderInGroup: 2,
      responseType: 'ordered_agreement',
      sourceRefs: [
        {
          sourceId: 'ess10-de-questionnaire',
          pdfPages: [6],
          originalForm: null,
          listLabelDe: null,
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'Stimme stark zu',
          labelEn: 'Agree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'Stimme zu',
          labelEn: 'Agree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'Weder noch',
          labelEn: 'Neither agree nor disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'Lehne ab',
          labelEn: 'Disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: 'Lehne stark ab',
          labelEn: 'Disagree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
      ],
      boundOriginalForm: 'Gedruckter Papierfragebogen (Selbstausfüllung)',
      codeBinding: {
        sourceId: 'ess10sc-original-codelists-direct',
        sourceFieldId: 'a5ea7e88-3e4d-416b-b4e0-74244c661f2d',
        sourceFieldMetadataVersion: 5,
        dataFileMetadataId: '178d1c16-db15-466e-b1a5-cea36109e089',
        dataFileMetadataVersion: 147,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5'],
      missingCodes: [
        { code: '7', reasonApi: 'Refusal', isMissingApi: true, printedCodeDe: null, labelDe: null },
        {
          code: '8',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '9',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS10SCe03_2:accalaw',
      studyId: 'ESS10SCe03_2',
      variable: 'accalaw',
      primaryTheme: 'democracy_authority',
      originalQuestionId: 'A51',
      wordingDe:
        'Wie akzeptabel wäre es für Sie, wenn Deutschland eine starke Führungsperson hätte, die über dem Gesetz steht?',
      introductionsDe: [],
      definitionDe: [],
      contextNotes: [
        'Bitte beantworten Sie alle Fragen nach dem heutigen Stand der Dinge, auch wenn dieser durch die Pandemie anders ist als sonst.',
      ],
      responseStemDe: null,
      situationDe: null,
      instructionDe: null,
      groupId: 'strong_leader',
      originalOrderInGroup: 1,
      responseType: 'ordered_acceptability',
      sourceRefs: [
        {
          sourceId: 'ess10-de-questionnaire',
          pdfPages: [6],
          originalForm: null,
          listLabelDe: null,
        },
      ],
      categories: [
        {
          code: '0',
          printedCodeDe: '0',
          labelDe: 'Überhaupt nicht akzeptabel',
          labelEn: 'Not at all acceptable',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: '1',
          labelEn: '1',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: '2',
          labelEn: '2',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: '3',
          labelEn: '3',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: '4',
          labelEn: '4',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: '5',
          labelEn: '5',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '6',
          printedCodeDe: '6',
          labelDe: '6',
          labelEn: '6',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '7',
          printedCodeDe: '7',
          labelDe: '7',
          labelEn: '7',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '8',
          printedCodeDe: '8',
          labelDe: '8',
          labelEn: '8',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '9',
          printedCodeDe: '9',
          labelDe: '9',
          labelEn: '9',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '10',
          printedCodeDe: '10',
          labelDe: 'Voll und ganz akzeptabel',
          labelEn: 'Completely acceptable',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
      ],
      boundOriginalForm: 'Gedruckter Papierfragebogen (Selbstausfüllung)',
      codeBinding: {
        sourceId: 'ess10sc-original-codelists-direct',
        sourceFieldId: 'a2ac2fd3-f8b4-4574-aa7b-0dbe75da4072',
        sourceFieldMetadataVersion: 3,
        dataFileMetadataId: '178d1c16-db15-466e-b1a5-cea36109e089',
        dataFileMetadataVersion: 147,
      },
      apiValidCodeOrder: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      missingCodes: [
        {
          code: '77',
          reasonApi: 'Refusal',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '88',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '99',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS10SCe03_2:loylead',
      studyId: 'ESS10SCe03_2',
      variable: 'loylead',
      primaryTheme: 'democracy_authority',
      originalQuestionId: 'A53',
      wordingDe:
        'Was Deutschland am meisten braucht, ist Loyalität gegenüber der politischen Führung.',
      introductionsDe: [
        'Wie sehr stimmen Sie jeder der folgenden Aussagen zu oder wie sehr lehnen Sie diese ab?',
        'Markieren Sie für jede Aussage ein Kästchen.',
      ],
      definitionDe: [],
      contextNotes: [
        'Bitte beantworten Sie alle Fragen nach dem heutigen Stand der Dinge, auch wenn dieser durch die Pandemie anders ist als sonst.',
        'A52 (Gehorsam und Respekt vor Autorität als Erziehungswerte) steht im selben Block und ist nicht ausgewählt.',
      ],
      responseStemDe: null,
      situationDe: null,
      instructionDe: null,
      groupId: 'authority_values',
      originalOrderInGroup: 2,
      responseType: 'ordered_agreement',
      sourceRefs: [
        {
          sourceId: 'ess10-de-questionnaire',
          pdfPages: [6],
          originalForm: null,
          listLabelDe: null,
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'Stimme stark zu',
          labelEn: 'Agree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'Stimme zu',
          labelEn: 'Agree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'Weder noch',
          labelEn: 'Neither agree nor disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'Lehne ab',
          labelEn: 'Disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: 'Lehne stark ab',
          labelEn: 'Disagree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess10-de-questionnaire',
          offeredOnWebsite: true,
        },
      ],
      boundOriginalForm: 'Gedruckter Papierfragebogen (Selbstausfüllung)',
      codeBinding: {
        sourceId: 'ess10sc-original-codelists-direct',
        sourceFieldId: '1ff9663e-8b7a-4948-add8-94ec706ceef6',
        sourceFieldMetadataVersion: 4,
        dataFileMetadataId: '178d1c16-db15-466e-b1a5-cea36109e089',
        dataFileMetadataVersion: 147,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5'],
      missingCodes: [
        { code: '7', reasonApi: 'Refusal', isMissingApi: true, printedCodeDe: null, labelDe: null },
        {
          code: '8',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '9',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
    {
      id: 'ESS5e03_6:prtyban',
      studyId: 'ESS5e03_6',
      variable: 'prtyban',
      primaryTheme: 'democracy_authority',
      originalQuestionId: 'B32',
      wordingDe:
        'Politische Parteien, die die Demokratie abschaffen wollen, sollten verboten werden',
      introductionsDe: [
        'Bitte schauen Sie jetzt auf Liste 12 und sagen Sie mir, wie sehr Sie jeder der folgenden Aussagen zustimmen oder wie sehr Sie diese ablehnen.',
      ],
      definitionDe: [],
      contextNotes: [
        'Die Antwortbeschriftungen stehen im Fragebogenkopf in Kleinschreibung; die Liste 12 selbst liegt nicht als eigenes Dokument vor.',
      ],
      responseStemDe: null,
      situationDe: null,
      instructionDe: null,
      groupId: 'party_ban',
      originalOrderInGroup: 1,
      responseType: 'ordered_agreement',
      sourceRefs: [
        {
          sourceId: 'ess5-de-questionnaire',
          pdfPages: [11, 12],
          originalForm: null,
          listLabelDe: null,
        },
      ],
      categories: [
        {
          code: '1',
          printedCodeDe: '1',
          labelDe: 'stimme stark zu',
          labelEn: 'Agree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess5-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '2',
          printedCodeDe: '2',
          labelDe: 'stimme zu',
          labelEn: 'Agree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess5-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '3',
          printedCodeDe: '3',
          labelDe: 'weder noch',
          labelEn: 'Neither agree nor disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess5-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '4',
          printedCodeDe: '4',
          labelDe: 'lehne ab',
          labelEn: 'Disagree',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess5-de-questionnaire',
          offeredOnWebsite: true,
        },
        {
          code: '5',
          printedCodeDe: '5',
          labelDe: 'lehne stark ab',
          labelEn: 'Disagree strongly',
          isMissingApi: false,
          semanticRole: 'substantive_response',
          labelSourceRef: 'ess5-de-questionnaire',
          offeredOnWebsite: true,
        },
      ],
      boundOriginalForm: 'Nationales Interviewskript (CAPI)',
      codeBinding: {
        sourceId: 'ess5-original-codelists-direct',
        sourceFieldId: '7adf3f75-50d1-4e38-9857-e1783b9950cc',
        sourceFieldMetadataVersion: 1,
        dataFileMetadataId: '0189b86b-8aa4-4be3-88ad-39c58b02f19f',
        dataFileMetadataVersion: 89,
      },
      apiValidCodeOrder: ['1', '2', '3', '4', '5'],
      missingCodes: [
        { code: '7', reasonApi: 'Refusal', isMissingApi: true, printedCodeDe: null, labelDe: null },
        {
          code: '8',
          reasonApi: "Don't know",
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
        {
          code: '9',
          reasonApi: 'No answer',
          isMissingApi: true,
          printedCodeDe: null,
          labelDe: null,
        },
      ],
      notAskedCodes: [],
    },
  ],
});
